/* eslint-disable max-classes-per-file */
import { ApiProperty } from '@nestjs/swagger';
import { IsBoolean, IsNumber, IsString } from 'class-validator';
import { SynologySuccessResponseDto } from '../synology.response.dto';
import { Transform } from 'class-transformer';

export class SynologyEntrySignInBodyDto {
  @IsString()
  declare __cIpHeRtExT: string;

  @Transform(({ value }) => Number.parseFloat(value))
  @IsNumber()
  declare client_time: number;
}

export class SynologyEntrySignInDataDto {
  /**
   * The device ID generated by the Synology NAS for the client application.  For this server this
   * is a bcrypt hash of the user agent string and session master key.
   */
  @IsString()
  declare did: string;

  /**
   * The session ID generated by the Synology NAS for the client application.  For this server this
   * is a bcrypt hash of the session master key, account session key, and session GUID.
   */
  @IsString()
  declare sid: string;

  /**
   * Flag for whether the client application is a portal application or not.  It is not clear what the
   * ramifications of this are.  This value is currently ignored.
   */
  @IsBoolean()
  declare is_portal_port: boolean;
}

export class SynologyEntrySignInResponseDto extends SynologySuccessResponseDto {
  @ApiProperty({
    type: SynologyEntrySignInDataDto,
  })
  declare data: SynologyEntrySignInDataDto;
}
